---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: test-configmap
#  namespace: default
#data:
#  foo: bar-1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: alpine
  namespace: default
spec:
  template:
    metadata:
      name: alpine
    spec:
      containers:
        - name: pi
          image: alpine
          command: ['cat', '/tmp/cm/foo']
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/cm
      volumes:
        - name: config-volume
          configMap:
            name: test-configmap
      restartPolicy: Never
---
